収入グラフデータの集計をJobで行う
nakatomoyanyan/household_account_book pull request #14
Opened 2024-12-25 06:38 UTC by nakatomoyanyan

* 作業時間
  * 12/4　1h17m
  * 12/5　3h38m
  * 12/8　2h18m
  * 12/10　4h24m
  * 12/11　3h
  * 12/12　2h8m
  * 12/13　30m
  * 12/16　1h25m
  * 12/17　3h
  * 12/18　2h49m
  * 12/19　1h29m
  * 12/24　30m
合計　26h28m
* 機能概要
  * solid queueをインストール
  * 収入画面におけるグラフのデータの集計を非同期処理で実装する
  * データが集計し終わっていない際に画面のグラフ描画部分に「データ集計中」のメッセージを表示
  * jobが失敗した場合に自動リトライをするように設定
* テスト
  * IncomesGrathモデルのテスト
  * householdコントローラーの#collecting_incomes_grath_dataのtest
  * IncomesGraphDataJobのテスト

2025-01-06 04:59 UTC, iwaguma-manabi requested changes

2025-01-06 04:59 UTC, iwaguma-manabi commented on household_account_book_app/app/jobs/incomes_graph_data_job.rb
> +  end
画面を開くたびに集計データが無限に作られそうですがどうでしょう？

2025-01-06 04:59 UTC, iwaguma-manabi commented on household_account_book_app/app/controllers/households_controller.rb
> +    @incomes_grath_data_this_year = current_user.incomes_graths.last.grath_data_this_year
２回目のアクセスでは残留している１回目の結果がすぐに取得されて２回目の結果を待たずにcompletedを返しそうですがどうでしょう？

2025-01-07 04:47 UTC, foolproof-htb commented on household_account_book_app/app/javascript/application.js
> +let shouldRetry = true;
この変数ってどこかで使われてますかね？
（私が見逃しているだけだったらすみません！）

2025-01-07 04:47 UTC, foolproof-htb commented on household_account_book_app/db/migrate/20241210055005_create_incomes_graph_data.rb
これはどっちでもいいかもですが、1プルリク内の範囲で作ったテーブルを drop する場合、create している migrate ファイルの方を削除した方がいいかもと思っています！
（migration をゼロから実行した際に、不要なテーブルが生み出され直後に削除される工程を挟んじゃうことになるので）

2025-01-07 04:47 UTC, foolproof-htb commented on household_account_book_app/config/environments/production.rb
> +
81行目に同じ設定が書かれていそうですが、同じ設定を複数行書いているのはなにか意図されたものですか？

2025-01-15 03:43 UTC, iwaguma-manabi commented on household_account_book_app/app/models/user.rb
> +  has_many :incomes_graths
各所で .last でしか取得していませんし、has_one の関係ではないでしょうか？

2025-01-15 03:49 UTC, iwaguma-manabi commented on household_account_book_app/app/controllers/households_controller.rb
> +    return unless latest_grath_data.nil? || incomes_updated_at > latest_grath_data.updated_at
ここ `> ` ではなく `>=` ではないでしょうか？
集計処理に時間がかかるのでもし時刻一致があるなら、集計完了と同時に入力した場合であり、再集計すべきかと思いましたがどうでしょう？
collecting_incomes_grath_data で使っている判定と同じ方が良いのでは？という考えもあります。

2025-01-15 03:50 UTC, iwaguma-manabi commented on household_account_book_app/app/controllers/households_controller.rb
> +    return unless latest_grath_data.nil? || incomes_updated_at > latest_grath_data.updated_at
また、もし同じ判定でにできるなら、この判定を関数として分離して双方で関数参照したほうが良いと思いましたがどうでしょう？
関数名が発生することで仕様が分かりやすくなり、共通可することで改修にも強くなります。

2025-01-15 03:52 UTC, iwaguma-manabi commented on household_account_book_app/app/controllers/households_controller.rb
> +    return unless latest_grath_data.nil? || incomes_updated_at > latest_grath_data.updated_at
いや集計しない場合の判定だから `>` が正しいのか collecting_incomes_grath_data 側を `>` にするのが正しい？

2025-01-15 05:05 UTC, iwaguma-manabi commented on household_account_book_app/app/controllers/households_controller.rb
> +    latest_grath_data = current_user.incomes_graths
細かいし判定処理でも参照する以上Railsがキャッシュして処理速度に差はなく動作としては問題ありませんが、人間の視認性という意味では if の片方でしか使わないものを事前に一時変数化するのは意味がなく混乱を招くため、一時変数は使わずif内で使う時にcurrent_userから参照するのはどうでしょう？

2025-01-15 05:10 UTC, iwaguma-manabi commented on household_account_book_app/app/models/user.rb
> +  has_one :incomes_graths, class_name: 'IncomesGrath'
has_one の関係性で良いならアソシエーション名も単数形にはならないでしょうか？
それとも月次年次の複数のデータがあるから単数形だと逆に混乱します？

あくまでグラフの種類としては一つの単数形であり、ただし値は一つではなく各関数で取得すると考えるとグラフは単数形のほうが、グラフ自体が複数あって配列データと誤認するような事を回避できて良さそうですがどうでしょう？

2025-01-15 06:07 UTC, iwaguma-manabi approved these changes

2025-01-17 04:09 UTC, SaitoJP approved these changes

2025-01-17 05:28 UTC, foolproof-htb commented
すみません、細かくて恐縮ですが、grath は graph の誤字かと思ってますがいかがですか？

2025-01-17 06:42 UTC, foolproof-htb approved these changes

2025-01-20 03:34 UTC, merged